"""Add OTP

Revision ID: 1b377095c9c8
Revises: 465a82af37c9
Create Date: 2026-03-18 13:31:37.108986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b377095c9c8'
down_revision: Union[str, None] = '465a82af37c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('registration_otp', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('registration_otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registration_otp_expires_at')
    op.drop_column('users', 'registration_otp')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
